export const dummyUserData = [
  {
    fid: 341482,
    username: "fardegods",
    displayName: "FarDeGods",
    pfpUrl: "https://i.imgur.com/LpNIY6Z.jpg",
    followerCount: 5349,
    newFollowers: 5349,
    followerIncrease: "100.00",
  },
  {
    fid: 276207,
    username: "ethpro",
    displayName: "ETHPro",
    pfpUrl: "https://i.imgur.com/BmFI9hi.jpg",
    followerCount: 797,
    newFollowers: 616,
    followerIncrease: "77.29",
  },
  {
    fid: 233147,
    username: "pplpleasr",
    displayName: "pplpleasr",
    pfpUrl: "https://i.imgur.com/vaLZIlg.jpg",
    followerCount: 746,
    newFollowers: 400,
    followerIncrease: "53.62",
  },
  {
    fid: 317812,
    username: "draball",
    displayName: "Degen Dragon🎩🐲",
    pfpUrl: "https://i.imgur.com/JtllMhz.png",
    followerCount: 682,
    newFollowers: 346,
    followerIncrease: "50.73",
  },
  {
    fid: 249078,
    username: "boostxyz",
    displayName: "Boost",
    pfpUrl: "https://i.imgur.com/FTch4Oj.jpg",
    followerCount: 562,
    newFollowers: 277,
    followerIncrease: "49.29",
  },
  {
    fid: 1134,
    username: "levy",
    displayName: "levy.eth",
    pfpUrl: "https://i.imgur.com/1IovpAV.jpg",
    followerCount: 2828,
    newFollowers: 1362,
    followerIncrease: "48.16",
  },
  {
    fid: 235074,
    username: "ahoy",
    displayName: "Ahoy",
    pfpUrl: "https://i.imgur.com/Gen7V0H.jpg",
    followerCount: 2377,
    newFollowers: 1040,
    followerIncrease: "43.75",
  },
  {
    fid: 303158,
    username: "teller.eth",
    displayName: "Teller",
    pfpUrl: "https://i.imgur.com/9DrXcJb.jpg",
    followerCount: 517,
    newFollowers: 188,
    followerIncrease: "36.36",
  },
  {
    fid: 308664,
    username: "9dccxyz",
    displayName: "9dcc",
    pfpUrl: "https://i.imgur.com/M566BBJ.jpg",
    followerCount: 4269,
    newFollowers: 1534,
    followerIncrease: "35.93",
  },
  {
    fid: 332281,
    username: "casterchain",
    displayName: "Casterchain",
    pfpUrl: "https://i.imgur.com/WbV7iQT.jpg",
    followerCount: 5324,
    newFollowers: 1776,
    followerIncrease: "33.36",
  },
  {
    fid: 16496,
    username: "nablafi",
    displayName: "Nabla Finance",
    pfpUrl: "https://i.imgur.com/NRJF4Ov.png",
    followerCount: 7644,
    newFollowers: 2241,
    followerIncrease: "29.32",
  },
  {
    fid: 269833,
    username: "simpsons",
    displayName: "Simpsons ERC404 - DeFi - NFTs ",
    pfpUrl: "https://i.imgur.com/rqlACjO.jpg",
    followerCount: 968,
    newFollowers: 278,
    followerIncrease: "28.72",
  },
  {
    fid: 266519,
    username: "alvanero",
    displayName: "Alvanero",
    pfpUrl:
      "https://ipfs.decentralized-content.com/ipfs/QmdqzhVvgVu7dzefgxmTMskM8CEPzytuqkVAcNtbbugf3f",
    followerCount: 586,
    newFollowers: 167,
    followerIncrease: "28.50",
  },
  {
    fid: 269694,
    username: "bitfloorsghost",
    displayName: "Bitfloorsghost",
    pfpUrl: "https://i.imgur.com/l9rlpqX.jpg",
    followerCount: 558,
    newFollowers: 155,
    followerIncrease: "27.78",
  },
  {
    fid: 233254,
    username: "lottopgf",
    displayName: "LottoPGF",
    pfpUrl: "https://i.imgur.com/5BDG2Oa.jpg",
    followerCount: 11638,
    newFollowers: 3131,
    followerIncrease: "26.90",
  },
  {
    fid: 252433,
    username: "ecosystem",
    displayName: "Ecosystem",
    pfpUrl: "https://i.imgur.com/t1P0Dns.gif",
    followerCount: 1808,
    newFollowers: 482,
    followerIncrease: "26.66",
  },
  {
    fid: 260050,
    username: "sameerkhan",
    displayName: "Muhammad Nihar",
    pfpUrl: "https://i.imgur.com/tUYYCzi.jpg",
    followerCount: 1079,
    newFollowers: 272,
    followerIncrease: "25.21",
  },
  {
    fid: 271991,
    username: "israfil",
    displayName: "Israfil 👾",
    pfpUrl: "https://i.imgur.com/XbU0QLb.jpg",
    followerCount: 1205,
    newFollowers: 302,
    followerIncrease: "25.06",
  },
  {
    fid: 20111,
    username: "lenspost",
    displayName: "LENSPOST LABS ",
    pfpUrl: "https://i.imgur.com/exxYltp.jpg",
    followerCount: 1778,
    newFollowers: 426,
    followerIncrease: "23.96",
  },
  {
    fid: 17542,
    username: "fard",
    displayName: "Kourosh",
    pfpUrl: "https://i.imgur.com/ROb7Wwy.jpg",
    followerCount: 3430,
    newFollowers: 793,
    followerIncrease: "23.12",
  },
  {
    fid: 270254,
    username: "xrmio",
    displayName: "ARMIN ",
    pfpUrl: "https://i.imgur.com/yX0i6Zd.jpg",
    followerCount: 785,
    newFollowers: 165,
    followerIncrease: "21.02",
  },
  {
    fid: 336550,
    username: "farsquirrel",
    displayName: "Farsquirrel🐿",
    pfpUrl: "https://i.imgur.com/YpViy9E.jpg",
    followerCount: 838,
    newFollowers: 175,
    followerIncrease: "20.88",
  },
  {
    fid: 286153,
    username: "imeboss",
    displayName: "Boss is here 😎👊",
    pfpUrl: "https://i.imgur.com/bnJcS3U.jpg",
    followerCount: 1536,
    newFollowers: 312,
    followerIncrease: "20.31",
  },
  {
    fid: 283780,
    username: "tomasalpha",
    displayName: "Alpha Hunter",
    pfpUrl: "https://i.imgur.com/FLvULWi.jpg",
    followerCount: 1085,
    newFollowers: 219,
    followerIncrease: "20.18",
  },
  {
    fid: 19289,
    username: "hassanbenam",
    displayName: "HaashB",
    pfpUrl: "https://i.imgur.com/k9CoiJB.jpg",
    followerCount: 2447,
    newFollowers: 487,
    followerIncrease: "19.90",
  },
  {
    fid: 278239,
    username: "!278239",
    displayName: "Strano",
    pfpUrl: "https://i.imgur.com/CpzsAMH.gif",
    followerCount: 534,
    newFollowers: 105,
    followerIncrease: "19.66",
  },
  {
    fid: 320216,
    username: "stormforce00",
    displayName: "Milk Man 🎩",
    pfpUrl: "https://i.imgur.com/1ItfPh6.jpg",
    followerCount: 981,
    newFollowers: 186,
    followerIncrease: "18.96",
  },
  {
    fid: 271601,
    username: "arbaz500",
    displayName: "Arbaz Ali",
    pfpUrl: "https://i.imgur.com/OhbRqC0.jpg",
    followerCount: 528,
    newFollowers: 100,
    followerIncrease: "18.94",
  },
  {
    fid: 278303,
    username: "highlights",
    displayName: "Highlight",
    pfpUrl: "https://i.imgur.com/RtdEf0P.jpg",
    followerCount: 525,
    newFollowers: 97,
    followerIncrease: "18.48",
  },
  {
    fid: 244902,
    username: "sartoshi",
    displayName: "sartoshi",
    pfpUrl: "https://i.imgur.com/UNRAUep.jpg",
    followerCount: 4674,
    newFollowers: 853,
    followerIncrease: "18.25",
  },
  {
    fid: 11512,
    username: "iamng",
    displayName: "ng",
    pfpUrl: "https://i.imgur.com/6AZYzca.jpg",
    followerCount: 620,
    newFollowers: 111,
    followerIncrease: "17.90",
  },
  {
    fid: 286046,
    username: "ilpyung",
    displayName: "ilpyung",
    pfpUrl: "https://i.imgur.com/uEcQmXt.jpg",
    followerCount: 550,
    newFollowers: 93,
    followerIncrease: "16.91",
  },
  {
    fid: 13861,
    username: "annacher",
    displayName: "anyaa.eth 👒🎩",
    pfpUrl: "https://i.imgur.com/CLiCEZJ.jpg",
    followerCount: 1417,
    newFollowers: 234,
    followerIncrease: "16.51",
  },
  {
    fid: 307159,
    username: "lintu",
    displayName: "Lintu|Fren3",
    pfpUrl: "https://i.imgur.com/kaKPJzJ.jpg",
    followerCount: 501,
    newFollowers: 77,
    followerIncrease: "15.37",
  },
  {
    fid: 14375,
    username: "mahan",
    displayName: "mahan",
    pfpUrl: "https://i.imgur.com/zylaMMY.jpg",
    followerCount: 620,
    newFollowers: 91,
    followerIncrease: "14.68",
  },
  {
    fid: 273014,
    username: "aldiodans",
    displayName: "Cat Bored 🐈",
    pfpUrl: "https://i.imgur.com/aqlO3mt.jpg",
    followerCount: 2268,
    newFollowers: 329,
    followerIncrease: "14.51",
  },
  {
    fid: 19380,
    username: "matin",
    displayName: "Farbod",
    pfpUrl: "https://i.imgur.com/kNE8eHD.jpg",
    followerCount: 553,
    newFollowers: 80,
    followerIncrease: "14.47",
  },
  {
    fid: 275795,
    username: "alexsakh",
    displayName: "Alex|fren3 🖼️",
    pfpUrl: "https://i.imgur.com/Yjblmu6.jpg",
    followerCount: 613,
    newFollowers: 84,
    followerIncrease: "13.70",
  },
  {
    fid: 253415,
    username: "lowan",
    displayName: "Lowan Kelly",
    pfpUrl: "https://i.imgur.com/C2ke098.jpg",
    followerCount: 1726,
    newFollowers: 229,
    followerIncrease: "13.27",
  },
  {
    fid: 248954,
    username: "lonliboy",
    displayName: "🌸 lonliboy 🌸",
    pfpUrl: "https://i.imgur.com/4X7zZqV.jpg",
    followerCount: 1426,
    newFollowers: 186,
    followerIncrease: "13.04",
  },
  {
    fid: 10178,
    username: "owl",
    displayName: "Hoot 🎩",
    pfpUrl: "https://i.imgur.com/rQj6wKT.jpg",
    followerCount: 2907,
    newFollowers: 379,
    followerIncrease: "13.04",
  },
  {
    fid: 9410,
    username: "gmoney.eth",
    displayName: "gmoney",
    pfpUrl: "https://i.imgur.com/Trq88ar.png",
    followerCount: 2543,
    newFollowers: 331,
    followerIncrease: "13.02",
  },
  {
    fid: 281630,
    username: "exmidas",
    displayName: "Exmidas",
    pfpUrl: "https://i.imgur.com/HOFuXE1.gif",
    followerCount: 719,
    newFollowers: 92,
    followerIncrease: "12.80",
  },
  {
    fid: 280260,
    username: "sevane",
    displayName: "Sevane",
    pfpUrl: "https://i.imgur.com/Cip2SVf.jpg",
    followerCount: 1172,
    newFollowers: 148,
    followerIncrease: "12.63",
  },
  {
    fid: 236238,
    username: "beyondclub",
    displayName: "beyondClub",
    pfpUrl: "https://i.imgur.com/GTY0OWG.jpg",
    followerCount: 5871,
    newFollowers: 721,
    followerIncrease: "12.28",
  },
  {
    fid: 16617,
    username: "henry14",
    displayName: "Herny 🖼️ fomoeb",
    pfpUrl: "https://i.imgur.com/a5AV97V.jpg",
    followerCount: 866,
    newFollowers: 106,
    followerIncrease: "12.24",
  },
  {
    fid: 4753,
    username: "saxenasaheb",
    displayName: "Saumya Saxena",
    pfpUrl: "https://i.imgur.com/ICvcPmC.jpg",
    followerCount: 2515,
    newFollowers: 305,
    followerIncrease: "12.13",
  },
  {
    fid: 306411,
    username: "0xscrip",
    displayName: "AI Crypto",
    pfpUrl:
      "https://ipfs.decentralized-content.com/ipfs/QmQoyHRwHMQBc4SSeaApLm3JbVdbzS1WpyfErhJ26mv3in/0",
    followerCount: 657,
    newFollowers: 79,
    followerIncrease: "12.02",
  },
  {
    fid: 276001,
    username: "!276001",
    displayName: "Irina_vka | fren3",
    pfpUrl: "https://i.imgur.com/oBcQlsS.jpg",
    followerCount: 769,
    newFollowers: 92,
    followerIncrease: "11.96",
  },
  {
    fid: 2270,
    username: "jalil",
    displayName: "jalil",
    pfpUrl: "https://i.imgur.com/HfO71Vw.gif",
    followerCount: 1352,
    newFollowers: 161,
    followerIncrease: "11.91",
  },
  {
    fid: 267965,
    username: "rollbit",
    displayName: "BuckTro",
    pfpUrl: "https://i.imgur.com/IMbwx20.jpg",
    followerCount: 1152,
    newFollowers: 132,
    followerIncrease: "11.46",
  },
  {
    fid: 16795,
    username: "alphacaster.eth",
    displayName: "Alphacaster 🖼️",
    pfpUrl: "https://i.imgur.com/yj6vsSR.png",
    followerCount: 1332,
    newFollowers: 152,
    followerIncrease: "11.41",
  },
  {
    fid: 296697,
    username: "framesbot",
    displayName: "framesbot",
    pfpUrl: "https://i.imgur.com/uFBZoiV.jpg",
    followerCount: 1011,
    newFollowers: 113,
    followerIncrease: "11.18",
  },
  {
    fid: 15357,
    username: "eclecticmethod",
    displayName: "Eclectic Method",
    pfpUrl: "https://i.imgur.com/4i08XG0.gif",
    followerCount: 1006,
    newFollowers: 110,
    followerIncrease: "10.93",
  },
  {
    fid: 223223,
    username: "hypoweb3dao",
    displayName: "Alpha Community web3",
    pfpUrl: "https://i.imgur.com/HDBHpPo.jpg",
    followerCount: 1223,
    newFollowers: 133,
    followerIncrease: "10.87",
  },
  {
    fid: 322783,
    username: "fcintern",
    displayName: "Farcaster Intern",
    pfpUrl: "https://i.imgur.com/ogXmpNH.gif",
    followerCount: 4880,
    newFollowers: 523,
    followerIncrease: "10.72",
  },
  {
    fid: 7620,
    username: "cybershakti",
    displayName: "Cyber Shakti ",
    pfpUrl: "https://i.imgur.com/pmpuWHc.jpg",
    followerCount: 6421,
    newFollowers: 669,
    followerIncrease: "10.42",
  },
  {
    fid: 265108,
    username: "omgidrawedit",
    displayName: "OMGiDRAWEDit",
    pfpUrl: "https://i.imgur.com/H8kKFwN.gif",
    followerCount: 968,
    newFollowers: 99,
    followerIncrease: "10.23",
  },
  {
    fid: 293524,
    username: "cryptoex",
    displayName: "FUN 🚀",
    pfpUrl: "https://i.imgur.com/RE3RfWb.jpg",
    followerCount: 3738,
    newFollowers: 381,
    followerIncrease: "10.19",
  },
  {
    fid: 311600,
    username: "anhelia",
    displayName: "Anhelia",
    pfpUrl: "https://i.imgur.com/0rGGh9x.jpg",
    followerCount: 1266,
    newFollowers: 129,
    followerIncrease: "10.19",
  },
  {
    fid: 287372,
    username: "rasulovna",
    displayName: "Gulnaz.Fren3",
    pfpUrl: "https://i.imgur.com/CtQSkOd.jpg",
    followerCount: 656,
    newFollowers: 66,
    followerIncrease: "10.06",
  },
  {
    fid: 250726,
    username: "seterror",
    displayName: "Seterror",
    pfpUrl: "https://i.imgur.com/XFV0WhI.jpg",
    followerCount: 2599,
    newFollowers: 257,
    followerIncrease: "9.89",
  },
  {
    fid: 274578,
    username: "cannoli",
    displayName: "MisterSweetTreat",
    pfpUrl: "https://i.imgur.com/xl7DHEg.jpg",
    followerCount: 600,
    newFollowers: 59,
    followerIncrease: "9.83",
  },
  {
    fid: 267828,
    username: "khryseis",
    displayName: "Max 🎩",
    pfpUrl: "https://i.imgur.com/Jlj2Ffw.jpg",
    followerCount: 958,
    newFollowers: 94,
    followerIncrease: "9.81",
  },
  {
    fid: 233030,
    username: "perfumer",
    displayName: "Alina / fren3 ",
    pfpUrl: "https://i.imgur.com/UlmZoMK.png",
    followerCount: 1193,
    newFollowers: 115,
    followerIncrease: "9.64",
  },
  {
    fid: 5860,
    username: "sum",
    displayName: "sumit 📚",
    pfpUrl:
      "https://ipfs.decentralized-content.com/ipfs/QmfSPY7NiiFiiDfhF77kAt8QEc9KyKMyAvnNQX9r4gDmXv/image.jpeg",
    followerCount: 743,
    newFollowers: 68,
    followerIncrease: "9.15",
  },
  {
    fid: 244566,
    username: "aqeel",
    displayName: "LUCIFER",
    pfpUrl: "https://i.imgur.com/l69FA3p.jpg",
    followerCount: 783,
    newFollowers: 70,
    followerIncrease: "8.94",
  },
  {
    fid: 242021,
    username: "farokh",
    displayName: "Farokh",
    pfpUrl: "https://i.imgur.com/dQ82ecG.jpg",
    followerCount: 4031,
    newFollowers: 354,
    followerIncrease: "8.78",
  },
  {
    fid: 281289,
    username: "tocd",
    displayName: "🎩The Old Castle Defense(TOCD)",
    pfpUrl: "https://i.imgur.com/j6AnizF.jpg",
    followerCount: 5492,
    newFollowers: 474,
    followerIncrease: "8.63",
  },
  {
    fid: 243270,
    username: "cryptocoins",
    displayName: "CRYPTOCOINS",
    pfpUrl: "https://i.imgur.com/eB6cCig.jpg",
    followerCount: 2903,
    newFollowers: 244,
    followerIncrease: "8.41",
  },
  {
    fid: 8276,
    username: "alpaca",
    displayName: "Tatyana SD 🖼️",
    pfpUrl:
      "https://i.seadn.io/gcs/files/8d9fe75356c9d18282ae9b24c3a76a6a.png?w=500&auto=format",
    followerCount: 2552,
    newFollowers: 212,
    followerIncrease: "8.31",
  },
  {
    fid: 243056,
    username: "ahmadzeeshan",
    displayName: "Ahmad Zeeshan ",
    pfpUrl: "https://i.imgur.com/1BJmw6D.jpg",
    followerCount: 1098,
    newFollowers: 91,
    followerIncrease: "8.29",
  },
  {
    fid: 192539,
    username: "yougogirl.eth",
    displayName: "ygg",
    pfpUrl: "https://i.imgur.com/gpqivz6.gif",
    followerCount: 3562,
    newFollowers: 295,
    followerIncrease: "8.28",
  },
  {
    fid: 300839,
    username: "airdropsepach",
    displayName: "0x-yu7u",
    pfpUrl: "https://i.imgur.com/Ulij4er.jpg",
    followerCount: 774,
    newFollowers: 64,
    followerIncrease: "8.27",
  },
  {
    fid: 6023,
    username: "stevedylandev.eth",
    displayName: "Steve",
    pfpUrl:
      "https://p765cpbvm0.execute-api.eu-central-1.amazonaws.com/p1/renderer/Minteeble/chain/base/collection/6e0b39a5-8569-4e67-b330-d352593c9629/image/176.png",
    followerCount: 2846,
    newFollowers: 234,
    followerIncrease: "8.22",
  },
  {
    fid: 244349,
    username: "threadguy",
    displayName: "thread",
    pfpUrl: "https://i.imgur.com/E0y8Amx.jpg",
    followerCount: 4214,
    newFollowers: 343,
    followerIncrease: "8.14",
  },
  {
    fid: 285086,
    username: "gaut",
    displayName: "gaut",
    pfpUrl: "https://i.imgur.com/b8a8Re6.jpg",
    followerCount: 2035,
    newFollowers: 165,
    followerIncrease: "8.11",
  },
  {
    fid: 251416,
    username: "afs",
    displayName: "afs ",
    pfpUrl: "https://i.imgur.com/Jqzt2ME.jpg",
    followerCount: 1162,
    newFollowers: 94,
    followerIncrease: "8.09",
  },
  {
    fid: 252221,
    username: "airdropsultan",
    displayName: "Mahendra",
    pfpUrl: "https://i.imgur.com/acC8I9n.jpg",
    followerCount: 2858,
    newFollowers: 229,
    followerIncrease: "8.01",
  },
  {
    fid: 211693,
    username: "mistershot",
    displayName: "Mistershot",
    pfpUrl: "https://i.imgur.com/miyXtl8.jpg",
    followerCount: 833,
    newFollowers: 66,
    followerIncrease: "7.92",
  },
  {
    fid: 248216,
    username: "sartocrates",
    displayName: "sartocrates",
    pfpUrl: "https://i.imgur.com/IjkcT3X.jpg",
    followerCount: 3071,
    newFollowers: 236,
    followerIncrease: "7.68",
  },
  {
    fid: 288578,
    username: "simbiryakov",
    displayName: "Evsim | Fren3",
    pfpUrl: "https://i.imgur.com/kdUJc4Q.jpg",
    followerCount: 1030,
    newFollowers: 79,
    followerIncrease: "7.67",
  },
  {
    fid: 216557,
    username: "mesed",
    displayName: "Mesed /  fren3 🖼️",
    pfpUrl: "https://i.imgur.com/q1FwkUY.jpg",
    followerCount: 1008,
    newFollowers: 77,
    followerIncrease: "7.64",
  },
  {
    fid: 16601,
    username: "rita",
    displayName: "Rita fren3🖼️",
    pfpUrl: "https://i.imgur.com/WEG2YQS.png",
    followerCount: 873,
    newFollowers: 66,
    followerIncrease: "7.56",
  },
  {
    fid: 267974,
    username: "bitcery",
    displayName: "Bitcery",
    pfpUrl: "https://arweave.net/EcCiz4oAZ-w2B9UgrZbwZRGjATMn49hqWonfk0E47Mo/",
    followerCount: 3929,
    newFollowers: 288,
    followerIncrease: "7.33",
  },
  {
    fid: 248389,
    username: "dylmusic",
    displayName: "Dyl",
    pfpUrl: "https://i.imgur.com/XNskoQz.jpg",
    followerCount: 1492,
    newFollowers: 108,
    followerIncrease: "7.24",
  },
  {
    fid: 252936,
    username: "nylonmaiden",
    displayName: "Nylon Maiden",
    pfpUrl: "https://i.imgur.com/5ZcEkf1.png",
    followerCount: 1106,
    newFollowers: 80,
    followerIncrease: "7.23",
  },
  {
    fid: 7941,
    username: "blablainvest",
    displayName: "sasha🍿",
    pfpUrl:
      "https://i.seadn.io/gcs/files/e91e906945bb77f98d6430d1e0ed6f8c.gif?w=500&auto=format",
    followerCount: 1845,
    newFollowers: 132,
    followerIncrease: "7.15",
  },
  {
    fid: 16616,
    username: "!16616",
    displayName: "Cryptopesik🖼️",
    pfpUrl:
      "https://ipfs.decentralized-content.com/ipfs/Qmat4Yava7jgT5zVh64zvrjm38yesjEcv1a88uD7gUubNg/338.webp",
    followerCount: 729,
    newFollowers: 52,
    followerIncrease: "7.13",
  },
  {
    fid: 278749,
    username: "sajid1980",
    displayName: "Muhammad Sajid",
    pfpUrl: "https://i.imgur.com/z9ZMBat.jpg",
    followerCount: 1618,
    newFollowers: 115,
    followerIncrease: "7.11",
  },
  {
    fid: 259023,
    username: "amarsadaqat",
    displayName: "Amarsadaqat",
    pfpUrl: "https://arweave.net/BW6kaAPSt2DqK72BASvd1dj0ZI21ibLhx_wsBhgFaK4/",
    followerCount: 735,
    newFollowers: 52,
    followerIncrease: "7.07",
  },
  {
    fid: 295684,
    username: "aishka",
    displayName: "Aishka/fren3🖼️ ",
    pfpUrl: "https://i.imgur.com/GBTJtQx.jpg",
    followerCount: 501,
    newFollowers: 35,
    followerIncrease: "6.99",
  },
  {
    fid: 253029,
    username: "x0xdead",
    displayName: "xxwil",
    pfpUrl: "https://i.imgur.com/2JLGieM.jpg",
    followerCount: 1199,
    newFollowers: 83,
    followerIncrease: "6.92",
  },
  {
    fid: 133,
    username: "nir",
    displayName: "nir.eth 🌿🟣🐦☁️",
    pfpUrl: "https://i.imgur.com/Ati4GoY.gif",
    followerCount: 11171,
    newFollowers: 770,
    followerIncrease: "6.89",
  },
  {
    fid: 20701,
    username: "chaps",
    displayName: "carlos",
    pfpUrl: "https://i.imgur.com/XGuOYf1.jpg",
    followerCount: 1195,
    newFollowers: 81,
    followerIncrease: "6.78",
  },
  {
    fid: 301276,
    username: "tahiyangan",
    displayName: "tahiyangan",
    pfpUrl: "https://i.imgur.com/EkC81l8.jpg",
    followerCount: 1668,
    newFollowers: 111,
    followerIncrease: "6.65",
  },
  {
    fid: 234616,
    username: "pichi",
    displayName: "PiChi",
    pfpUrl: "https://i.imgur.com/ymuNAVR.jpg",
    followerCount: 1964,
    newFollowers: 129,
    followerIncrease: "6.57",
  },
  {
    fid: 6111,
    username: "funghibull",
    displayName: "Funghibull",
    pfpUrl: "https://i.imgur.com/mulG4Zw.jpg",
    followerCount: 1571,
    newFollowers: 102,
    followerIncrease: "6.49",
  },
  {
    fid: 12309,
    username: "jethid",
    displayName: "J.eth.id 🎩🧑‍🌾 @ethxy",
    pfpUrl: "https://i.imgur.com/YM4KuCy.jpg",
    followerCount: 6522,
    newFollowers: 423,
    followerIncrease: "6.49",
  },
  {
    fid: 211832,
    username: "miasoarez",
    displayName: "Mia",
    pfpUrl: "https://i.imgur.com/Ij22ROW.jpg",
    followerCount: 5985,
    newFollowers: 380,
    followerIncrease: "6.35",
  },
];
